services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - postgres
      - pgadmin

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    depends_on:
      - postgres
