services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - db
      - pgadmin

  db:
    image: postgres
    env_file:
      - .env.production
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    env_file:
      - .env.production
    ports:
      - '5050:80'
    depends_on:
      - db
